name: Generate and Deploy CineVerse

on:
  push:
    branches:
      - main
    paths:
      - "imdb_list.json"
      - "scripts/generate_movies.py"
      - "requirements.txt"
      - "index.html"
      - "movie.html"
      - "player.html"
      - "css/**"
      - "js/**"
      - "assets/**"

  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:

  build-and-deploy:

    runs-on: ubuntu-latest

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:

      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Generate movies.json
        env:
          TMDB_API_TOKEN: ${{ secrets.TMDB_API_TOKEN }}
        run: |
          python scripts/generate_movies.py

      - name: Configure GitHub Pages
        uses: actions/configure-pages@v5

      - name: Upload website
        uses: actions/upload-pages-artifact@v4
        with:
          path: "."

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
