name: Generate and Deploy CineVerse

on:
  push:
    branches:
      - main
    paths:
      - "imdb_list.json"
      - "scripts/generate_movies.py"
      - "requirements.txt"
      - "index.html"
      - "movie.html"
      - "player.html"
      - "css/**"
      - "js/**"
      - "assets/**"

  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

concurrency:
  group: cineverse-pages
  cancel-in-progress: true

jobs:

  build-and-deploy:

    runs-on: ubuntu-latest

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:

      # ==========================================
      # Checkout repository
      # ==========================================

      - name: Checkout repository
        uses: actions/checkout@v6


      # ==========================================
      # Setup Python
      # ==========================================

      - name: Setup Python
        uses: actions/setup-python@v7
        with:
          python-version: "3.11"
          cache: "pip"


      # ==========================================
      # Install dependencies
      # ==========================================

      - name: Install dependencies
        run: |
          pip install -r requirements.txt


      # ==========================================
      # Generate movies.json
      # ==========================================

      - name: Generate movies.json
        env:
          TMDB_API_TOKEN: ${{ secrets.TMDB_API_TOKEN }}
        run: |
          python scripts/generate_movies.py


      # ==========================================
      # Commit generated movies.json
      # ==========================================

      - name: Commit updated movies.json
        run: |

          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          git add data/movies.json

          if git diff --cached --quiet; then
            echo "No changes to movies.json"
          else
            git commit -m "Auto update movies.json"
            git push
          fi


      # ==========================================
      # Configure GitHub Pages
      # ==========================================

      - name: Configure GitHub Pages
        uses: actions/configure-pages@v6


      # ==========================================
      # Upload website
      # ==========================================

      - name: Upload website
        uses: actions/upload-pages-artifact@v5
        with:
          path: "."


      # ==========================================
      # Deploy GitHub Pages
      # ==========================================

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v5
